themeVolume: theme # no trailing slash
sidenav: true
enabledPrezs:
  - VocPrez
  - SpacePrez
sparqlCreds:
  VocPrez:
    SPARQL_ENDPOINT: #{VOCPREZ_SPARQL_ENDPOINT}#
    SPARQL_USERNAME: #{VOCPREZ_SPARQL_USERNAME}#
    SPARQL_PASSWORD: #{VOCPREZ_SPARQL_PASSWORD}#
  SpacePrez:
    SPARQL_ENDPOINT: #{SPACEPREZ_SPARQL_ENDPOINT}#
    SPARQL_USERNAME: #{SPACEPREZ_SPARQL_USERNAME}#
    SPARQL_PASSWORD: #{SPACEPREZ_SPARQL_PASSWORD}#
  CatPrez:
    SPARQL_ENDPOINT: null
    SPARQL_USERNAME: null
    SPARQL_PASSWORD: null
  TimePrez:
    SPARQL_ENDPOINT: null
    SPARQL_USERNAME: null
    SPARQL_PASSWORD: null
port: 8000
demo: true
debug: true
allowPartialResults: true
searchEndpoints:
  - name: GA VocPrez
    url: http://ga.surroundaustralia.com/sparql/
  - name: GGIC VocPrez
    url: http://ggic.surroundaustralia.com/sparql/
  - name: DAWE VocPrez
    url: http://dawe.surroundaustralia.com/sparql/
  - name: ICSM VocPrez
    url: http://icsm.surroundaustralia.com/sparql/
  - name: CSIRO VocPrez
    url: http://csiro.surroundaustralia.com/sparql/
systemUri: https://prez.surroundaustralia.com
systemInfo:
  Prez:
    title: SURROUND Prez
    desc: Prez demo instance for SURROUND Australia
  VocPrez:
    title: SURROUND Vocabularies
    desc: Demo vocabularies
    data_uri: http://exampledata.org
  SpacePrez:
    title: SURROUND Spatial Data
    desc: Floods spatial data
    data_uri: http://exampledata.org
  CatPrez:
    title: null
    desc: null
    data_uri:
  TimePrez:
    title: null
    desc: null
    data_uri:
appName: surround
email: jamie.feiss@surroundaustralia.com
deploymentMethod: kubernetes # docker, kubernetes or ecs
storageClass: ebs-sc # for kubernetes deployment
version: 0.2.1
