services:
  prez:
    container_name: #{APP_NAME}#-prez
    image: surroundaustralia/prez:#{VERSION}#
    ports:
      - "8000:8000"
    environment:
      SYSTEM_URI: #{SYSTEM_URI}#
      DEBUG: #{DEBUG}#
      DEMO: #{DEMO}#
      ALLOW_PARTIAL_RESULTS: #{ALLOW_PARTIAL_RESULTS}#
      SPARQL_CREDS: #{SPARQL_CREDS}#
      ENABLED_PREZS: #{ENABLED_PREZS}#
      THEME_VOLUME: #{THEME_VOLUME}#
      SIDENAV: #{SIDENAV}#
      SEARCH_ENDPOINTS: #{SEARCH_ENDPOINTS}#
      SYSTEM_INFO: #{SYSTEM_INFO}#
    volumes:
      - ../#{THEME_VOLUME}#:/app/prez/#{THEME_VOLUME}#
