apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: #{APP_NAME}#-prez-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: #{STORAGE_CLASS}#
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: #{APP_NAME}#-prez-config
data:
  SYSTEM_URI: #{SYSTEM_URI}#
  DEBUG: #{DEBUG}#
  DEMO: #{DEMO}#
  ALLOW_PARTIAL_RESULTS: #{ALLOW_PARTIAL_RESULTS}#
  SPARQL_CREDS: #{SPARQL_CREDS}#
  ENABLED_PREZS: #{ENABLED_PREZS}#
  THEME_VOLUME: #{THEME_VOLUME}#
  SIDENAV: #{SIDENAV}#
  SEARCH_ENDPOINTS: #{SEARCH_ENDPOINTS}#
  SYSTEM_INFO: #{SYSTEM_INFO}#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: #{APP_NAME}#-prez-deployment
  labels:
    app: #{APP_NAME}#
spec:
  replicas: 1
  selector:
    matchLabels:
      app: #{APP_NAME}#
  template:
    metadata:
      labels:
        app: #{APP_NAME}#
    spec:
      containers:
        - name: #{APP_NAME}#-prez
          image: surroundaustralia/prez:#{VERSION}#
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "250m"
          ports:
            - containerPort: #{PORT}#
          envFrom:
            - configMapRef:
                name: #{APP_NAME}#-prez-config
          volumeMounts:
            - mountPath: /app/prez/#{THEME_VOLUME}#
              name: #{THEME_VOLUME}#
      volumes:
        - name: #{THEME_VOLUME}#
          persistentVolumeClaim:
            claimName: #{APP_NAME}#-prez-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: #{APP_NAME}#-prez-service
spec:
  selector:
    app: #{APP_NAME}#
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: #{PORT}#
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: #{APP_NAME}#-prez-issuer
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: #{EMAIL}#
    privateKeySecretRef:
      name: #{APP_NAME}#-prez-issuer
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: #{APP_NAME}#-prez-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-buffer-size: 8k
    cert-manager.io/cluster-issuer: "#{APP_NAME}#-prez-issuer"
spec:
  tls:
    - hosts:
        - #{SYSTEM_URI_HOST}#
      secretName: #{APP_NAME}#-prez-cert
  rules:
    - host: #{SYSTEM_URI_HOST}#
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: #{APP_NAME}#-prez-service
                port:
                  number: 80
